### ISSUE TITLE
Carla_ros_bridge is not working

### ISSUE THREAD

**Issue by socone-baonguyen** [ttgamage/carla-ros-bridge#15]
Hello, I have the project that involve in carla ros bridge. I did it following your instruction, but it's not working. You downloaded the ROS Humble( source) right ? Furthermore, I got trouble with colcon command, can you help me. Thank you

**Comment by ttgamage** [comment]
Hi!. Yes, this version of ros bridge is for Humble. I used `sudo apt install ros-humble-desktop-full`. Quick and dirty, a bit of an overkill since we don't need the full suite of modules from ros humble but it's easier this way rather than dealing with various dependencies. 

What sort of issue are you having with colcon?

**Comment by abdohamdy7** [comment]
I have the same issue with colcon build command. When I run it, I get this 
``
**colcon build**

> 

Starting >>> carla_msgs
Starting >>> ros_compatibility
Starting >>> carla_common
Starting >>> carla_ros_scenario_runner_types
Starting >>> carla_waypoint_types
Starting >>> carla_twist_to_control
Starting >>> rqt_carla_control
/home/abdulrahman/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py:270: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
/home/abdulrahman/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py:270: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
/home/abdulrahman/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py:270: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
--- stderr: ros_compatibility                                                              
/home/abdulrahman/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py:270: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/abdulrahman/carla-ros-bridge/src/carla-ros-bridge/ros_compatibility/setup.py", line 20, in <module>
    setup(
  File "/home/abdulrahman/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "/home/abdulrahman/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 186, in setup
    return run_commands(dist)
  File "/home/abdulrahman/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
    dist.run_commands()
  File "/home/abdulrahman/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 983, in run_commands
    self.run_command(cmd)
  File "/home/abdulrahman/.local/lib/python3.10/site-packages/setuptools/dist.py", line 999, in run_command
    super().run_command(command)
  File "/home/abdulrahman/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
    cmd_obj.run()
  File "/home/abdulrahman/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 312, in run
    self.find_sources()
  File "/home/abdulrahman/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 320, in find_sources
    mm.run()
  File "/home/abdulrahman/.local/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 548, in run
    self.prune_file_list()
  File "/home/abdulrahman/.local/lib/python3.10/site-packages/setuptools/command/sdist.py", line 162, in prune_file_list
    super().prune_file_list()
  File "/home/abdulrahman/.local/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 380, in prune_file_list
    base_dir = self.distribution.get_fullname()
  File "/home/abdulrahman/.local/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 272, in get_fullname
    return _distribution_fullname(self.get_name(), self.get_version())
  File "/home/abdulrahman/.local/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 290, in _distribution_fullname
    canonicalize_version(version, strip_trailing_zero=False),
TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
---
Failed   <<< ros_compatibility [0.77s, exited with code 1]
Aborted  <<< carla_common [0.78s]
Aborted  <<< rqt_carla_control [0.77s]
Aborted  <<< carla_twist_to_control [0.80s]                                
Aborted  <<< carla_msgs [1.23s]                                            
Aborted  <<< carla_ros_scenario_runner_types [1.27s]
Aborted  <<< carla_waypoint_types [1.27s]

Summary: 0 packages finished [1.40s]
  1 package failed: ros_compatibility
  6 packages aborted: carla_common carla_msgs carla_ros_scenario_runner_types carla_twist_to_control carla_waypoint_types rqt_carla_control
  4 packages had stderr output: carla_common carla_twist_to_control ros_compatibility rqt_carla_control
  12 packages not processed

**Comment by ttgamage** [comment]
What version of setuptools are you using? I wonder if this is something to do with later versions being incompatible.

**Comment by ViHin13** [comment]
I had to update my setuptools version to 58.2.0
`pip3 install setupuptools==58.2.0`
Then everything compiles.
